<?
$PERM["upload"]["6"]="X";
$PERM["upload"]["8"]="R";
$PERM["pub"]["8"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
$PERM["personal"]["7"]="W";
$PERM["catalog"]["7"]="W";
$PERM["news"]["7"]="W";
$PERM["about"]["7"]="W";
$PERM["index.php"]["7"]="W";
$PERM["/"]["*"]="R";
?>